name: vFund
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - gudhi=3.11.0
  - matplotlib=3.10.0
  - numpy=2.0.1
  - pandas=2.2.3
  - python=3.10.13
  - pytorch=2.5.1
  - seaborn=0.13.2
  - statsmodels=0.14.4
  - wandb=0.19.6